# Generated by Django 3.0.8 on 2020-07-31 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='available_rooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='bond_amt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='rent',
            field=models.IntegerField(default=0),
        ),
    ]
