# Generated by Django 3.0.8 on 2020-07-31 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20200731_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='approved',
            field=models.IntegerField(default=0),
        ),
    ]
