# Generated by Django 3.0.8 on 2020-08-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_auto_20200731_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='listed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='approved',
            field=models.IntegerField(default=2),
        ),
    ]
