# Generated by Django 3.0.8 on 2020-08-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_auto_20200801_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='available_rooms',
        ),
        migrations.AddField(
            model_name='property',
            name='available_from',
            field=models.DateField(auto_now=True),
        ),
    ]
